num_models: 1
model:
  pretrained_model_path:
    - Qwen/Qwen2.5-3B-Instruct
  device: "cuda"
  dtype: bfloat16
  attn_impl: "sdpa"  
data:
  name: gsm8k
training:
  epochs: 1
  random_seed: 1337
  max_prompt_len: 256
  max_gen_len: 128  
  temperature: 1.0  
  batch_size: 64
  num_questions_per_batch: 32
  num_answers_per_question: 4 
  micro_batch_size: 1 
  max_grad_norm: 1.0
  learning_rate: 1.0e-5
  weight_decay: 0.0
  betas: [0.9, 0.999]
  ckpt_dir: "ckpt"
  log_dir: "logs"
  ckpt_save_interval: 1000  
  eval_interval: 10
  memory_efficient_adamw: false